# Generated by Django 2.2.16 on 2023-03-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20230311_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Если хотите прикрепить картинку к посту, это можно сделать здесь.', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
